[package]
name = "untitled_game"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = { version = "0.15", features = ["serialize"] }
avian3d = "0"
serde = { version = "1", features = ["derive"] }
serde_json = { version = "1"}
